### ISSUE TITLE
Allow users to delete their own recipse

### ISSUE THREAD

**Issue by kerfootj** [kerfootj/cookbook#49]

**Comment by drwm-base** [comment]
Hi @kerfootj I would like to work on this pull request, can you give me any more information on what you want exactly?

**Comment by kerfootj** [comment]
@drwm-base sorry but I'm not really looking for help, it's just a personal project that I work on in my spare time. Feel free to fork the repository if you want to play around with the code. Just note that it does rely on the server code found [here](https://github.com/kerfootj/cookbook-server), and mongodb.
